### ISSUE TITLE
search.py does not run because it is missing a parameter GridSearchCV

### ISSUE THREAD

**Issue by ksrinivs64** [KangchengHou/gntk#2]
`    clf = GridSearchCV(svc, {'C' : C_list}, 
                cv=zip(train_fold_idx, test_fold_idx),
                n_jobs=80, verbose=0, return_train_score=True)`

I think you need something similar for return_train_score=True on line:
`    clf = GridSearchCV(svc, {'C' : C_list},
                cv=zip(train_fold_idx, test_fold_idx),
                n_jobs=80, verbose=0)`?

**Comment by KangchengHou** [comment]
Thanks for pointing this out! This is indeed a bug. We just fixed in https://github.com/KangchengHou/gntk/commit/6ef1eb9de8ce4d8f83512bde216acbc84a329406
